### PR TITLE
TriSYCL compatibility for SYCLParallelSTL

### PR DESCRIPTION
**Pull request by a-doumoulakis**
Here is the pull request from the triSYCL branch @keryell and @JoanThibault have been working on. 

The branch has been tested with triSYCL and all tests and benchmarks execute successfully with and without OpenCL enabled.

Unfortunately due to issue #26 I was not able to test it with ComputeCPP but it should be compatible. Most of the changes where made by @JoanThibault so I am not that familiar with the code but from what I see, the changes brought to the algorithms to make them work with triSYCL have been done in a way that makes ComputeCPP use the original version.

### Sidenote

After comparing this branch with the [hierachical parallelism branch](https://github.com/JoanThibault/SyclParallelSTL/tree/hie-par-dev "Branch") from pull request #21, I believe that all changes brought in #21 are present in this pull request as well.

### CODE REVIEW

**Comment by keryell** [comment]
@Ruyk I have the feeling that this should be merged and the other issues should be addressed in other PR:
- use Docker + Ubuntu 17.04 to have a modern version of everything to have travis-CI + triSYCL happy;
- solve the kernel naming issue of the version using hierarchical parallelism and move 1 bit at a time the implementation using hierarchical parallelism, even with ComputeCpp.

**Comment by Ruyk** [comment]
This changeset is too large for me to review it. Does it work also on ComputeCpp?

**Comment by keryell** [comment]
Your Travis-CI says that it works with ComputeCpp. :-)
Mainly because most of the extensions are used only in triSYCL mode for now.

**Comment by Ruyk** [comment]
Interesting, because the master branch is red (There have been changes on the OpenCL ICD and Header repositories) :-) I'll just go ahead and merge it.
Thanks!

**Pull request merged**
