### PR TITLE
Updated to ComputeCpp CE 0.8.0

### PR DESCRIPTION
**Pull request by Rbiessy**

### CODE REVIEW

**Comment by Ruyk** [comment]
Seems triSYCL is broken, can you disable triSYCL from travis? Just mark it as optional pass

**Comment by Rbiessy** [comment]
I can't find how to do that :/
On a side note I noticed that CMakeLists.txt adds -DSYCL_PSTL_USE_OLD_ALGO meaning that I actually haven't really tested this changes yet.

**Comment by Rbiessy** [comment]
The tests fail badly when I compile them without SYCL_PSTL_USE_OLD_ALGO, it makes my gpu idle and forces me to reboot my machine. I have the same issue with older commits. Do we want to make this work or should we always use the old algo?

**Comment by Ruyk** [comment]
Keep the USE_OLD_ALGO , the other branch is not fully tested.

**Comment by keryell** [comment]
ah yes, you are using the new 1.2.1 ``h_item`` now... I need to implement them.

**Comment by Rbiessy** [comment]
@keryell There also seemed to have some issues in https://github.com/KhronosGroup/SyclParallelSTL/pull/74 with the `get_info` method: https://travis-ci.org/KhronosGroup/SyclParallelSTL/jobs/382202541

**Comment by keryell** [comment]
Yes, I have to implement this too. Actually it needs some refactoring to be more friendly with virtual inheritance inside triSYCL...

**Pull request merged**
