### PR TITLE
Add implemented algorithms missing from README.MD

### PR DESCRIPTION
**Pull request by tremmelg**

### CODE REVIEW

**Comment by Ruyk** [comment]
LGTM, feel free to merge when Travis finishes

**Comment by tremmelg** [comment]
Looks like the link for the Intel OpenCL runtime is dead at the moment. It hasn't been updated on their webpage either.

**Comment by Ruyk** [comment]
@tremmelg downloading and testing the intel opencl should be made optional (if the download link fails, travis should not fail). Can you create an issue to fix this on a separate issue? Apart from that, looks fine.

**Comment by tremmelg** [comment]
Yes, that sounds good as we can't really do anything about it until the link is fixed.

**Comment by keryell** [comment]
Can it work with PoCL instead?

**Pull request merged**
